In [2]:
# Exercice 1

import numpy as np

In [3]:
array_0_to_9 = np.arange(10)
array_0_to_9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Exercice 2

float_list = [3.14, 2.17, 0, 1, 2]

int_array = np.array(float_list, dtype=int)
int_array

array([3, 2, 0, 1, 2])

In [7]:
# Exercice 3

array_3x3 = np.arange(1, 10).reshape(3, 3)
array_3x3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Exercice 4




In [10]:
# Exercice 5

array = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

In [11]:
second_row = array[1]
print(second_row)

[20 21 22 23 24]


In [12]:
# Exercice 6

arr = np.arange(10)

reversed_arr = arr[::-1]

print(reversed_arr)


[9 8 7 6 5 4 3 2 1 0]


In [13]:
# Exercice 7

identity_matrix = np.identity(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# Exercice 8

arr = np.arange(10)

total = np.sum(arr)
average = np.mean(arr)

print(f"Sum: {total}, Average: {average}")

Sum: 45, Average: 4.5


In [15]:
# Exercice 10

arr = np.arange(10)

odd_numbers = arr[arr % 2 == 1]

print(odd_numbers)

[1 3 5 7 9]
