In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [3]:
# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3]
#  [4 5 6]]

# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)


1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


In [4]:
# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

Shape: (2, 3)
Size: 6
Data Type: int64


In [5]:
array_1d = np.array([1, 2, 3, 4])
# Output: 1D Array: [1 2 3 4], Shape: (4,), Size: 4

1. Create Arrays: Create a 1D array with numbers from 1 to 5 and a 2D array with numbers from 1 to 6 (reshape it to have 2 rows and 3 columns).

USE:(https://numpy.org/doc/stable/reference/generated/numpy.reshape.html), (https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

2. Inspect Attributes: For each array you created, print its shape, size, and data type.

3. Play with Data Types: Create a new array with numbers from 1 to 3, but specify the data type as float. Check and print its data type.

Expected Output:

Prints of the created arrays with their respective shapes, sizes, and data types.
An array with a specified data type different from the default.

In [6]:
import numpy as np
# 1D array
array_1d = np.arange(1, 6)
# 2D array
array_2d = np.arange(1, 7).reshape(2, 3)

In [7]:
# Attributes of the 1D array
print("1D Array:")
print("Array:", array_1d)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data type:", array_1d.dtype)
# Attributes of the 2D array
print("\n2D Array:")
print("Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data type:", array_2d.dtype)

1D Array:
Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data type: int64

2D Array:
Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64


In [8]:
# Array with specified data type
array_float = np.arange(1, 4, dtype=float)
print("\nArray with float data type:")
print("Array:", array_float)
print("Data type:", array_float.dtype)


Array with float data type:
Array: [1. 2. 3.]
Data type: float64


A one dimensional array with the temperatures from this week.
A two dimensional array of shape 2,5 with random values (choose them yourself) from 1 to 10.
A 3D array with valid pixel values for a picture with 9 pixels.

In [9]:
import numpy as np
# Temperatures for a week (example)
temperatures = np.array([22, 24, 19, 23, 25, 20, 21])
print("1D Array - Temperatures:")
print(temperatures)

1D Array - Temperatures:
[22 24 19 23 25 20 21]


In [10]:
# 2D Array with random values
random_2d = np.array([[3, 5, 7, 2, 9],
                      [8, 6, 4, 1, 10]])
print("\n2D Array with random values:")
print(random_2d)


2D Array with random values:
[[ 3  5  7  2  9]
 [ 8  6  4  1 10]]


In [11]:
# 3D Array for 9 pixels (3x3 grid) with RGB values
pixels = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    [[255, 255, 0], [0, 255, 255], [255, 0, 255]],
    [[128, 128, 128], [64, 64, 64], [192, 192, 192]]
])
print("\n3D Array - Pixels:")
print(pixels)



3D Array - Pixels:
[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [  0 255 255]
  [255   0 255]]

 [[128 128 128]
  [ 64  64  64]
  [192 192 192]]]


1. Basic Indexing: Create an array of 10 elements and access the 5th element in it.

2. Basic Slicing: From the same array, extract a slice containing the 3rd to the 8th elements.

3. Boolean Indexing: Create an array of 6 random integers between 10 and 50. Print the elements that are greater than 30.

4. Fancy Indexing: From the same array, use fancy indexing to access the 2nd, 4th, and 6th elements.

Expected Output:

The 5th element of the first array.
A slice of the array showing elements from the 3rd to the 8th position.
Elements greater than 30 from the random array.
Selected elements (2nd, 4th, 6th) from the random array using fancy indexing.

In [12]:
import numpy as np
# Create an array with 10 elements
array_10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Access the 5th element (index 4)
fifth_element = array_10[4]
print("5th element:", fifth_element)

5th element: 5


In [13]:
# Extract elements from the 3rd to the 8th position (indices 2 to 7)
slice_array = array_10[2:8]
print("Slice from 3rd to 8th elements:", slice_array)

Slice from 3rd to 8th elements: [3 4 5 6 7 8]


In [14]:
# Create an array of 6 random integers between 10 and 50
random_array = np.random.randint(10, 50, 6)
# Boolean indexing to find elements greater than 30
greater_than_30 = random_array[random_array > 30]
print("Random array elements greater than 30:", greater_than_30)

Random array elements greater than 30: [47 46]


In [15]:
# Use fancy indexing to access 2nd, 4th, and 6th elements
fancy_elements = random_array[[1, 3, 5]]
print("Elements at 2nd, 4th, and 6th positions:", fancy_elements)


Elements at 2nd, 4th, and 6th positions: [12 46 16]


After learning about array indexing and slicing, it's important to practice these concepts. Here are some exercises to help solidify your understanding:

1. Modifying Specific Elements:

Create an array with values from 1 to 10. Change the value of the fifth element to 50.

2. Slicing and Modifying a Range:

Given an array of 10 elements, modify the elements from index 3 to 7 to be their negative equivalent.

3. Conditional Modification with Boolean Indexing:

Create an array with 20 random integers between 1 and 100. Set all values greater than 50 to -1.

4. Advanced Indexing Modification:

Given a 2D array of shape (5, 5), modify the elements in the diagonal to be twice their original value.

5. Understanding Slicing Impact:

Create an array of 10 elements. Slice the array from index 2 to 5, and modify the first element of the slice. Observe the change in the original array.

In [16]:
# Modify elements from index 3 to 7
array[3:8] = -array[3:8]
print("Array after negating elements 3 to 7:", array)

NameError: name 'array' is not defined

In [17]:
# Random array with values between 1 and 100
random_array = np.random.randint(1, 101, 20)
# Set elements greater than 50 to -1
random_array[random_array > 50] = -1
print("Array after setting values > 50 to -1:", random_array)

Array after setting values > 50 to -1: [27 23 -1 50 -1 38 18 10 -1 -1 11 -1 32 -1 -1 35 -1 -1 -1  4]


1. Reshape Array: Create a 1D array with 12 elements and reshape it to a 4x3 matrix. Then reshape it to a 2x6 matrix.

2. Transpose Matrix: Transpose the 2x6 matrix you created in the previous step.

3. Combine Reshaping and Transposing: Create a 3x4 matrix, transpose it, and then reshape the transposed matrix to a 1D array.

In [19]:
import numpy as np
# Create a 1D array with 12 elements
array_1d = np.arange(12)
# Reshape to 4x3 matrix
matrix_4x3 = array_1d.reshape(4, 3)
print("4x3 Matrix:\n", matrix_4x3)
# Reshape to 2x6 matrix
matrix_2x6 = array_1d.reshape(2, 6)
print("\n2x6 Matrix:\n", matrix_2x6)

4x3 Matrix:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

2x6 Matrix:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [20]:
# Create a 3x4 matrix
matrix_3x4 = np.arange(12).reshape(3, 4)
print("\n3x4 Matrix:\n", matrix_3x4)
# Transpose the 3x4 matrix
transposed_3x4 = matrix_3x4.T
print("\nTransposed 3x4 Matrix:\n", transposed_3x4)
# Reshape the transposed matrix to a 1D array
reshaped_1d = transposed_3x4.reshape(-1)
print("\nReshaped 1D Array from Transposed Matrix:\n", reshaped_1d)


3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transposed 3x4 Matrix:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Reshaped 1D Array from Transposed Matrix:
 [ 0  4  8  1  5  9  2  6 10  3  7 11]
